### ISSUE TITLE
Remote validation not working with custom error message due to type conversion problems

### ISSUE THREAD

**Issue by vsajip** [jquery-validation/jquery-validation#2258]
### Summary

According to the documentation, a server end-point for remote validation can return a simple string (other than "true" or "false") to indicate a custom error message. However, I am having some problems getting this to work as advertised.

### Environment
Version of `jquery-validate`: 1.19.0 with jQuery 3.3.1
Which browser and its version: Chromium Version 71.0.3578.98 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

The remote validation is configured using
```
remote: {
  "url": "https://alpha.red-dove.com/",
  "dataType": "text/plain"
}
```
The URL for the remote validation - https://alpha.red-dove.com/ - is set up to always return the fixed string `'Not available for now!'`, no matter what parameters you pass to it. The response is sent as `text/plain` and with a suitable CORS header so that there is no CORS-related failure.

### Steps to reproduce

1. Visit the fiddle https://jsfiddle.net/vsajip/ygh1cep5/
1. Use right-click  Inspect on the target pane, and set breakpoints in `jquery.js` at lines 9255 and 8789 (this is an exception handler).
1. Paste a valid email address in the "Email address" field in the fiddle, then tab off the field to trigger validation.

### Expected behaviour
There shouldn't be any exceptions relating to data conversion, so the validation error should be clear. However, an exception _is_ hit, but it's not detectable from higher levels - I had to do some digging in the jQuery sources to find what looks like the problem.

### Actual behaviour

The breakpoint at `jquery.js` line 9255 is hit, and looking at the variables it's clear that the `response` variable is set to `'Not available for now!'`, as expected. When you run from this point, an exception is thrown and the breakpoint at line 8789 is hit with the error

```
TypeError: conv is not a function
    at ajaxConvert (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js:8787:19)
    at done (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js:9255:15)
    at XMLHttpRequest.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js:9548:9)
```

As a result of the exception, the "success" code in jquery-validate.js at line 1585 is never hit, so no validation error message is shown.

While this is seemingly not an error in the jquery-validate code itself, it might be to do with how the AJAX call is internally configured by `jquery-validate`. Alternatively, it might be that I'm doing something wrong in the configuration, but AFAICT I'm going by what it says in the documentation.

**Comment by vsajip** [comment]
Sorry for the noise. Found the misconfiguration, should have been `dataType: "text"`
